version: "3.8"

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3,lambda,glue,athena
      - DEBUG=${DEBUG:-0}
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - ls_network

networks:
  ls_network:
    driver: bridge